# codemagic.yaml
workflows:
  ios-workflow:
    name: Uluslararasi Alevi Vakfi iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials # Bu grupta API Key verileriniz olmalı
      vars:
        XCODE_BUNDLE_ID: "com.alevivakfi.uade"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.alevivakfi.uade
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods

    scripts:
      - name: Flutter Paketlerini Yukle
        script: |
          flutter pub get
          flutter clean
          flutter pub get

      - name: iOS Yapilandirmasini Olustur (0 Dependencies Fix)
        script: |
          # podhelper.rb dosyasını sertifika istemeden zorla üretir
          flutter build ios --config-only --no-codesign

      - name: Apple Sertifikalarini ve Profillerini Otomatik Olustur/Cek
        script: |
          # Bu komut Apple portalına gider, profil yoksa --create ile kendisi olusturur
          # Module not found hatalarını önlemek için imzalama dosyalarını hazırlar
          app-store-connect fetch-signing-files "$XCODE_BUNDLE_ID" --type IOS_APP_STORE --create
          
          # Xcode projesine bu profilleri bağlar
          xcode-project use-profiles

      - name: CocoaPods Kurulumu (Module Not Found Fix)
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Flutter IPA Build
        script: |
          # export_options.plist artık use-profiles tarafından oluşturuldu
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
