workflows:
  ios-workflow:
    name: Uluslararasi Alevi Vakfi iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    # HATAYI ÇÖZEN KRİTİK EKLENTİ:
    integrations:
      app_store_connect: alevi-vakfi # Buraya Codemagic panelinde verdiğin entegrasyon adını yaz (Genelde 'alevi-vakfi' veya 'default')

    environment:
      groups:
        - app_store_credentials # Bu grubun App Store Connect API Keylerini içerdiğinden emin ol
      vars:
        BUNDLE_ID: "com.alevivakfi.uade"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter SDK Paket Kurulumu
        script: |
          flutter pub get
          flutter clean
          flutter pub get

      - name: iOS Yapılandırma ve Bağımlılık Onarımı (0 Dependencies Fix)
        script: |
          # Sertifika hatası almadan podhelper.rb dosyasını oluşturur
          flutter build ios --config-only --no-codesign
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Apple Sertifikalarını Yapılandır
        script: |
          # Bu komut Apple Developer portalından doğru profilleri çeker
          xcode-project use-profiles --bundle-id $BUNDLE_ID --export-method app-store

      - name: Flutter IPA Build (Release Modu)
        script: |
          # build ipa komutu otomatik olarak imzalama yapar
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration # Yukarıdaki 'integrations' bloğu ile eşleşir
        submit_to_testflight: true
