workflows:
  ios-workflow:
    name: Uluslararasi Alevi Vakfi iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials # Bu grupta APP_STORE_CONNECT_PRIVATE_KEY, KEY_IDENTIFIER ve ISSUER_ID olmalı
      vars:
        BUNDLE_ID: "com.alevivakfi.uade"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter SDK Paket Kurulumu
        script: |
          flutter pub get
          flutter clean
          flutter pub get

      - name: iOS Yapılandırma ve Bağımlılık Onarımı (0 Dependencies Fix)
        script: |
          # podhelper.rb dosyasını oluşturmak için kritik adım
          flutter build ios --config-only --no-codesign
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Apple Sertifikalarını Yapılandır
        script: |
          # 'alevi-vakfi' ismini burada doğrudan referans veriyoruz
          xcode-project use-profiles --bundle-id $BUNDLE_ID --export-method app-store

      - name: Flutter IPA Build
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # 'auth: integration' yerine doğrudan API Key bilgilerini kullanıyoruz
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
