environment:
  groups:
    - app_store_credentials
  vars:
    XCODE_BUNDLE_ID: "com.alevivakfi.uade"
  ios_signing:
    distribution_type: app_store
    bundle_identifier: com.alevivakfi.uade
  flutter: stable
  xcode: latest

scripts:
  # ... (pub get ve pod install adımları aynı kalsın) ...

  - name: Apple Sertifikalarini Yapilandir
    script: |
      # --auth-type=api_key ekleyerek Codemagic'e portalına erişim yetkisi veriyoruz
      # Bu sayede eksik profilleri kendisi de oluşturabilir/çekebilir.
      xcode-project use-profiles --bundle-id com.alevivakfi.uade --export-method app-store
