workflows:
  ios-free-ipa:
    name: Ücretsiz iOS IPA (gerçek telefonda çalışır)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        GYM_CODE_SIGNING_IDENTITY: ""
        GYM_BUILD_PATH: ""
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: iOS build (no signing)
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r9 uluslararasialevivakfi2.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Payload/Runner.app
