# 1. Flutter'ın pod yardımcı dosyasını içeri aktarıyoruz (Hatanın çözümü burada)
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

platform :ios, '14.0' # Sürümü 14'e sabitledik

target 'Runner' do
  use_frameworks! # Swift eklentileri (Hive/Path Provider) için zorunlu
  use_modular_headers!

  # 2. Artık Ruby bu komutu tanıyacak
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Gereksiz derleme hatalarını önlemek için ayarlar
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end